# Generated by Django 4.2.4 on 2023-08-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category_name')),
                ('description', models.TextField(verbose_name='category_description')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('price', models.IntegerField(verbose_name='price')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('change_date', models.DateField(verbose_name='last_change_date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
