# Generated by Django 4.2.4 on 2023-08-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='category_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Catalog.category', verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
